% Analyze_Adaptation_Staircase.m
clear all;
close all;


% % For checking single data files use this format - easeir than importing
% % .mat file list
% datalist = ["102423_oo_6_Data.mat"];

% Define the file containing the list of .mat file names
cd P:\labFolderNew\Bikalpa\matlab_base\project_human_psych\psychophysics_pairvunpair\Data
[fileList,pname] = uigetfile('*.txt','pick a filename file');

% Read the file names from the text file
fileID = fopen(fileList, 'r');
fileNames = textscan(fileID, '%s', 'Delimiter', '\n');
fileNames = fileNames{1};
fclose(fileID);

% Loop through the file names and load the corresponding .mat files
for i = 1:numel(fileNames)
    try
        data{i} = load(fileNames{i}); % Load the .mat file
    catch
        fprintf('Error loading %s\n', fileNames{i});
    end

% Access the loaded data, e.g., data{1}, data{2}, etc.
trialdata = data{i}(1);

responsedata = cell2mat({trialdata.randomTrialFinalData.response}); 
trialsdata = cell2mat({trialdata.randomTrialFinalData.trials}); 
combine_data = [trialsdata' responsedata'];

% Assuming combine_data is an Nx2 matrix with trial numbers in column 1 and responses in column 2

% Initialize result matrix
result = zeros(10, 5); % 10 trials, 4 columns (trial number, number of runs, sum of -1s, sum of 1s)

% Process each trial
for trial = 1:10
    % Find rows for the current trial
    trial_rows = combine_data(:,1) == trial;

    % Count the number of runs for this trial
    num_runs = sum(trial_rows);

    % Sum responses for -1, 0, and 1
    sum_minus_one = sum(combine_data(trial_rows, 2) == -1);
    sum_zero = sum(combine_data(trial_rows, 2) == 0);
    sum_one = sum(combine_data(trial_rows, 2) == 1);

    % Store in result matrix
    result(trial, :) = [trial, num_runs, sum_minus_one, sum_zero, sum_one];
    
end

    segPer = result(:,3) ./ (result(:,3) + result(:,5) + result(:,4));
    segPer(isnan(segPer)) = 0;
    result = [result segPer];

    segPer2 = result(:,3) ./ (result(:,3) + result(:,5));
    segPer2(isnan(segPer2)) = 0;
    result = [result segPer2];

    segNull = result(:,4) ./ (result(:,3) + result(:,5) + result(:,4));
    segNull(isnan(segNull)) = 0;
    result = [result segNull];

    result_cumulation(:,:,i) = result;
    
end 
%32413

%%
start = 1;
step = 5; 
figure; 
subplot(1,3,1)
errorbar(mean(result_cumulation(:,6,1:3),3),...
    std(result_cumulation(:,6,1:3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,4:5),3),...
    std(result_cumulation(:,6,4:5),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,6:9),3),...
    std(result_cumulation(:,6,6:9),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,10),3),...
    std(result_cumulation(:,6,10),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,11:13),3),...
    std(result_cumulation(:,6,11:13),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_3div345= [mean(result_cumulation(:,6,1:3),3)...
    std(result_cumulation(:,6,1:3),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,4:5),3)...
    std(result_cumulation(:,6,4:5),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,6:9),3)...
    std(result_cumulation(:,6,6:9),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,10),3)...
    std(result_cumulation(:,6,10),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,11:13),3)...
    std(result_cumulation(:,6,11:13),0,3)./sqrt(step)];

subplot(1,3,2) 
errorbar(mean(result_cumulation(:,7,1:3),3),...
    std(result_cumulation(:,7,1:3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,4:5),3),...
    std(result_cumulation(:,7,4:5),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,6:9),3),...
    std(result_cumulation(:,7,6:9),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,10),3),...
    std(result_cumulation(:,7,10),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,11:13),3),...
    std(result_cumulation(:,7,11:13),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_3div35= [mean(result_cumulation(:,7,1:3),3)...
    std(result_cumulation(:,7,1:3),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,4:5),3)...
    std(result_cumulation(:,7,4:5),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,6:9),3)...
    std(result_cumulation(:,7,6:9),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,10),3)...
    std(result_cumulation(:,7,10),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,11:13),3)...
    std(result_cumulation(:,7,11:13),0,3)./sqrt(step)];

subplot(1,3,3)
errorbar(mean(result_cumulation(:,8,1:3),3),...
    std(result_cumulation(:,8,1:3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,4:5),3),...
    std(result_cumulation(:,8,4:5),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,6:9),3),...
    std(result_cumulation(:,8,6:9),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,10),3),...
    std(result_cumulation(:,8,10),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,11:13),3),...
    std(result_cumulation(:,8,11:13),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_4div345= [mean(result_cumulation(:,8,1:3),3)...
    std(result_cumulation(:,8,1:3),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,4:5),3)...
    std(result_cumulation(:,8,4:5),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,6:9),3)...
    std(result_cumulation(:,8,6:9),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,10),3)...
    std(result_cumulation(:,8,10),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,11:13),3)...
    std(result_cumulation(:,8,11:13),0,3)./sqrt(step)];
%%
start = 1;
step = 5; 
figure; 
subplot(1,3,1)
errorbar(mean(result_cumulation(:,6,start:step),3),...
    std(result_cumulation(:,6,start:step),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,step*1+start:step*2),3),...
    std(result_cumulation(:,6,step*1+start:step*2),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,step*2+start:step*3),3),...
    std(result_cumulation(:,6,step*2+start:step*3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,step*3+start:step*4),3),...
    std(result_cumulation(:,6,step*3+start:step*4),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,step*4+start:step*5),3),...
    std(result_cumulation(:,6,step*4+start:step*5),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_3div345= [mean(result_cumulation(:,6,start:step),3)...
    std(result_cumulation(:,6,start:step),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,step*1+start:step*2),3)...
    std(result_cumulation(:,6,step*1+start:step*2),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,step*2+start:step*3),3)...
    std(result_cumulation(:,6,step*2+start:step*3),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,step*3+start:step*4),3)...
    std(result_cumulation(:,6,step*3+start:step*4),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,step*4+start:step*5),3)...
    std(result_cumulation(:,6,step*4+start:step*5),0,3)./sqrt(step)];

subplot(1,3,2) 
errorbar(mean(result_cumulation(:,7,start:step),3),...
    std(result_cumulation(:,7,start:step),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,step*1+start:step*2),3),...
    std(result_cumulation(:,7,step*1+start:step*2),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,step*2+start:step*3),3),...
    std(result_cumulation(:,7,step*2+start:step*3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,step*3+start:step*4),3),...
    std(result_cumulation(:,7,step*3+start:step*4),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,step*4+start:step*5),3),...
    std(result_cumulation(:,7,step*4+start:step*5),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_3div35= [mean(result_cumulation(:,7,start:step),3)...
    std(result_cumulation(:,7,start:step),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,step*1+start:step*2),3)...
    std(result_cumulation(:,7,step*1+start:step*2),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,step*2+start:step*3),3)...
    std(result_cumulation(:,7,step*2+start:step*3),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,step*3+start:step*4),3)...
    std(result_cumulation(:,7,step*3+start:step*4),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,step*4+start:step*5),3)...
    std(result_cumulation(:,7,step*4+start:step*5),0,3)./sqrt(step)];

subplot(1,3,3)
errorbar(mean(result_cumulation(:,8,start:step),3),...
    std(result_cumulation(:,8,start:step),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,step*1+start:step*2),3),...
    std(result_cumulation(:,8,step*1+start:step*2),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,step*2+start:step*3),3),...
    std(result_cumulation(:,8,step*2+start:step*3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,step*3+start:step*4),3),...
    std(result_cumulation(:,8,step*3+start:step*4),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,step*4+start:step*5),3),...
    std(result_cumulation(:,8,step*4+start:step*5),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_4div345= [mean(result_cumulation(:,8,start:step),3)...
    std(result_cumulation(:,8,start:step),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,step*1+start:step*2),3)...
    std(result_cumulation(:,8,step*1+start:step*2),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,step*2+start:step*3),3)...
    std(result_cumulation(:,8,step*2+start:step*3),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,step*3+start:step*4),3)...
    std(result_cumulation(:,8,step*3+start:step*4),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,step*4+start:step*5),3)...
    std(result_cumulation(:,8,step*4+start:step*5),0,3)./sqrt(step)];


cd P:\labFolderNew\Steven\MotionRepulsionData\Adaptation\PsychophysicsData\Owen_data
