% Analyze_Adaptation_Staircase.m
clear all;
% close all;


% % For checking single data files use this format - easeir than importing
% % .mat file list
% datalist = ["102423_oo_6_Data.mat"];

% Define the file containing the list of .mat file names
cd P:\labFolderNew\Rohit\pUpRandomPL_Data\RB
[fileList,pname] = uigetfile('*.txt','pick a filename file');

% Read the file names from the text file
fileID = fopen(fileList, 'r');
fileNames = textscan(fileID, '%s', 'Delimiter', '\n');
fileNames = fileNames{1};
fclose(fileID);

% Loop through the file names and load the corresponding .mat files

data = load(fileNames{1}); % Load the .mat file


% Access the loaded data, e.g., data{1}, data{2}, etc.
trialdata = data(1);

responsedata = cell2mat({trialdata.randomTrialFinalData.response}); 
trialsdata = cell2mat({trialdata.randomTrialFinalData.trials}); 
% combine_data = [trialsdata' responsedata'];

numTrials = length({trialdata.randomTrialFinalData.trials});
for j = 1:numTrials
    if strcmp(trialdata.randomTrialFinalData(j).direction, 'left')
        direction(j, 1) = -1; % Assign -1 for "Left"
    else
        direction(j, 1) = 1;  % Assign 1 for "Right"
    end
end

combine_data = [trialsdata' responsedata' direction ];
sorted_combine_data = sortrows(combine_data,3);

% Assuming combine_data is an Nx2 matrix with trial numbers in column 1 and responses in column 2

% Initialize result matrix
result = zeros(10, 5); % 10 trials, 4 columns (trial number, number of runs, sum of -1s, sum of 1s)

% Process each trial
for trial = 1:10
    % Find rows for the current trial
    sorted_combine_dataL = sorted_combine_data(1:50,:);
    sorted_combine_dataR = sorted_combine_data(51:100,:);

    trial_rows_L = sorted_combine_dataL(:,1) == trial;
    trial_rows_R = sorted_combine_dataR(:,1) == trial;

    % Count the number of runs for this trial
    num_runsL = sum(trial_rows_L);
    num_runsR = sum(trial_rows_R);


    % Sum responses for -1, 0, and 1
    sum_minus_one = sum(sorted_combine_dataL(trial_rows_L, 2) == -1);
    sum_zero = sum(sorted_combine_dataL(trial_rows_L, 2) == 0);
    sum_one = sum(sorted_combine_dataL(trial_rows_L, 2) == 1);

    sum_minus_oneR = sum(sorted_combine_dataR(trial_rows_R, 2) == -1);
    sum_zeroR = sum(sorted_combine_dataR(trial_rows_R, 2) == 0);
    sum_oneR = sum(sorted_combine_dataR(trial_rows_R, 2) == 1);

    % Store in result matrix
    resultL(trial, :) = [trial, num_runsL, sum_minus_one, sum_zero, sum_one];
    resultR(trial, :) = [trial, num_runsR, sum_minus_oneR, sum_zeroR, sum_oneR];
    
end

%     segPer = result(:,3) ./ (result(:,3) + result(:,5) + result(:,4));
%     segPer(isnan(segPer)) = 0;
%     result = [result segPer];

    segPer2 = resultL(:,3) ./ (resultL(:,3) + resultL(:,5));
    segPer2(isnan(segPer2)) = 0;
    resultL = [resultL segPer2];

%     segNull = result(:,4) ./ (result(:,3) + result(:,5) + result(:,4));
%     segNull(isnan(segNull)) = 0;
%     result = [result segNull];


    segPer2 = resultR(:,3) ./ (resultR(:,3) + resultR(:,5));
    segPer2(isnan(segPer2)) = 0;
    resultR = [resultR segPer2];


%%

figure; 
plot(0.1:0.1:1,resultL(:,6),'k-'); hold on;
plot(0.1:0.1:1,resultR(:,6),'r-'); hold on; 
legend ('L','R');


start = 1;
step = 5; 
figure; 
subplot(1,3,1)
errorbar(mean(result_cumulation(:,6,1:3),3),...
    std(result_cumulation(:,6,1:3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,4:5),3),...
    std(result_cumulation(:,6,4:5),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,6:9),3),...
    std(result_cumulation(:,6,6:9),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,10),3),...
    std(result_cumulation(:,6,10),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,11:13),3),...
    std(result_cumulation(:,6,11:13),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_3div345= [mean(result_cumulation(:,6,1:3),3)...
    std(result_cumulation(:,6,1:3),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,4:5),3)...
    std(result_cumulation(:,6,4:5),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,6:9),3)...
    std(result_cumulation(:,6,6:9),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,10),3)...
    std(result_cumulation(:,6,10),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,11:13),3)...
    std(result_cumulation(:,6,11:13),0,3)./sqrt(step)];

subplot(1,3,2) 
errorbar(mean(result_cumulation(:,7,1:3),3),...
    std(result_cumulation(:,7,1:3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,4:5),3),...
    std(result_cumulation(:,7,4:5),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,6:9),3),...
    std(result_cumulation(:,7,6:9),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,10),3),...
    std(result_cumulation(:,7,10),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,11:13),3),...
    std(result_cumulation(:,7,11:13),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_3div35= [mean(result_cumulation(:,7,1:3),3)...
    std(result_cumulation(:,7,1:3),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,4:5),3)...
    std(result_cumulation(:,7,4:5),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,6:9),3)...
    std(result_cumulation(:,7,6:9),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,10),3)...
    std(result_cumulation(:,7,10),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,11:13),3)...
    std(result_cumulation(:,7,11:13),0,3)./sqrt(step)];

subplot(1,3,3)
errorbar(mean(result_cumulation(:,8,1:3),3),...
    std(result_cumulation(:,8,1:3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,4:5),3),...
    std(result_cumulation(:,8,4:5),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,6:9),3),...
    std(result_cumulation(:,8,6:9),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,10),3),...
    std(result_cumulation(:,8,10),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,11:13),3),...
    std(result_cumulation(:,8,11:13),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_4div345= [mean(result_cumulation(:,8,1:3),3)...
    std(result_cumulation(:,8,1:3),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,4:5),3)...
    std(result_cumulation(:,8,4:5),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,6:9),3)...
    std(result_cumulation(:,8,6:9),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,10),3)...
    std(result_cumulation(:,8,10),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,11:13),3)...
    std(result_cumulation(:,8,11:13),0,3)./sqrt(step)];
%%
start = 1;
step = 5; 
figure; 
subplot(1,3,1)
errorbar(mean(result_cumulation(:,6,start:step),3),...
    std(result_cumulation(:,6,start:step),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,step*1+start:step*2),3),...
    std(result_cumulation(:,6,step*1+start:step*2),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,step*2+start:step*3),3),...
    std(result_cumulation(:,6,step*2+start:step*3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,step*3+start:step*4),3),...
    std(result_cumulation(:,6,step*3+start:step*4),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,6,step*4+start:step*5),3),...
    std(result_cumulation(:,6,step*4+start:step*5),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_3div345= [mean(result_cumulation(:,6,start:step),3)...
    std(result_cumulation(:,6,start:step),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,step*1+start:step*2),3)...
    std(result_cumulation(:,6,step*1+start:step*2),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,step*2+start:step*3),3)...
    std(result_cumulation(:,6,step*2+start:step*3),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,step*3+start:step*4),3)...
    std(result_cumulation(:,6,step*3+start:step*4),0,3)./sqrt(step)...
    mean(result_cumulation(:,6,step*4+start:step*5),3)...
    std(result_cumulation(:,6,step*4+start:step*5),0,3)./sqrt(step)];

subplot(1,3,2) 
errorbar(mean(result_cumulation(:,7,start:step),3),...
    std(result_cumulation(:,7,start:step),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,step*1+start:step*2),3),...
    std(result_cumulation(:,7,step*1+start:step*2),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,step*2+start:step*3),3),...
    std(result_cumulation(:,7,step*2+start:step*3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,step*3+start:step*4),3),...
    std(result_cumulation(:,7,step*3+start:step*4),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,7,step*4+start:step*5),3),...
    std(result_cumulation(:,7,step*4+start:step*5),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_3div35= [mean(result_cumulation(:,7,start:step),3)...
    std(result_cumulation(:,7,start:step),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,step*1+start:step*2),3)...
    std(result_cumulation(:,7,step*1+start:step*2),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,step*2+start:step*3),3)...
    std(result_cumulation(:,7,step*2+start:step*3),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,step*3+start:step*4),3)...
    std(result_cumulation(:,7,step*3+start:step*4),0,3)./sqrt(step)...
    mean(result_cumulation(:,7,step*4+start:step*5),3)...
    std(result_cumulation(:,7,step*4+start:step*5),0,3)./sqrt(step)];

subplot(1,3,3)
errorbar(mean(result_cumulation(:,8,start:step),3),...
    std(result_cumulation(:,8,start:step),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,step*1+start:step*2),3),...
    std(result_cumulation(:,8,step*1+start:step*2),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,step*2+start:step*3),3),...
    std(result_cumulation(:,8,step*2+start:step*3),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,step*3+start:step*4),3),...
    std(result_cumulation(:,8,step*3+start:step*4),0,3)./sqrt(step)); hold on;
errorbar(mean(result_cumulation(:,8,step*4+start:step*5),3),...
    std(result_cumulation(:,8,step*4+start:step*5),0,3)./sqrt(step)); hold on;
legend('3','4','5','6','7')

SegPer_4div345= [mean(result_cumulation(:,8,start:step),3)...
    std(result_cumulation(:,8,start:step),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,step*1+start:step*2),3)...
    std(result_cumulation(:,8,step*1+start:step*2),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,step*2+start:step*3),3)...
    std(result_cumulation(:,8,step*2+start:step*3),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,step*3+start:step*4),3)...
    std(result_cumulation(:,8,step*3+start:step*4),0,3)./sqrt(step)...
    mean(result_cumulation(:,8,step*4+start:step*5),3)...
    std(result_cumulation(:,8,step*4+start:step*5),0,3)./sqrt(step)];


cd P:\labFolderNew\Steven\MotionRepulsionData\Adaptation\PsychophysicsData\Owen_data
